useWidgetAction: Fix actionConfirmation config obj regression
Action confirmation with the config object failed with:

```
Failed to perform action TypeError: confirmText.startsWith is not a function
```

Signed-off-by: Florian Hotze <dev@florianhotze.com>