Sitemap edit: Fix save button not working due to JSON error (#3300)
Fixes #3290.

Fixes
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'slots' -> object with constructor 'Object'
    |     property 'widgets' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    --- property 'parent' closes the circle
```
when trying to save a sitemap.

Signed-off-by: Florian Hotze <dev@florianhotze.com>