Items list: Fix searchbar broken after Items list update & Fix search query not stored (#2184)
Fixes #1334.
Fixes #1702.

After editing or removing an Item, the searchbar of the Items list was
sometimes not working anymore. Console then showed this error:
```
TypeError: undefined is not an object (evaluating
'n.virtualList.params')
```
  
It seems that this was caused because the replaceAllItems operation was
applied on the virtual list without re-rendering the searchbar
afterward.

The search query was forgotten when the Items list reloaded or the 
Items list page was re-entered from an Item detail page.
This is also fixed by using `$f7.data` to store the query.

---------

Signed-off-by: Florian Hotze <florianh_dev@icloud.com>