[Blockly] Fix HTTP POST and PUT generator signatures with headers
Ensure HttpPostRequest and HttpPutRequest fall back to the 5-argument
signature (url, contentType, content, headers, timeout) when headers
are present, preventing Java NoSuchMethodError runtime exceptions when
contentType is set to 'none'.

Signed-off-by: Jimmy Tanagra <jcode@tanagra.id.au>