[Blockly] Fix HTTP POST and PUT generator signatures with headers (#4459)
Ensure HttpPostRequest and HttpPutRequest fall back to the 5-argument
signature (url, contentType, content, headers, timeout) when headers are
present, preventing Java NoSuchMethodError runtime exceptions when
contentType is set to `none`.

Previously, when selecting POST/PUT with `Content-type: none` and some headers,
a call to the the 3-argument version `sendXxxxxRequest(url, headers, timeout)`
which doesn't exist for POST/PUT was generated. See
https://www.openhab.org/javadoc/latest/org/openhab/core/model/script/actions/http

-----

Signed-off-by: Jimmy Tanagra <jcode@tanagra.id.au>
(cherry picked from commit 6bfed0a6f683659b5bad7d515def27a05f4d290e)